In [99]:
#import pkgs
from citipy import citipy
import openweathermapy as ow
import pandas as pd
import json, requests

import numpy
from random import uniform

#import API key
from config import key

In [100]:
# Create a settings dictionary with your API key and preferred units
settings = {"units": "imperial", "appid": key}

In [101]:
#Randomly select at least 500 unique (non-repeat) cities based on latitude and longitude.
#use citipy to get a list

# Latitude values are measured relative to the equator and range from -90° at the 
#South Pole to +90° at the North Pole. 
#Longitude values are measured relative to the prime meridian. 
#They range from -180° when traveling west to 180° when traveling east. 
coord_list = []

lat = numpy.random.uniform(low=-90, high=90, size=2000)
lng = numpy.random.uniform(low=-180, high=180, size=2000)
#zip the lists into a tuple
coordinates = zip(lat,lng)
# convert so it can print
coordinates = set(coordinates)

for coordinate_pair in coordinates:
    lat, lon = coordinate_pair
    coord_list.append(citipy.nearest_city(lat, lon))
    #print (lat, lon)

#convert coordinates to city names for API calls
city_list = []

for coords in coord_list:
    city = coords.city_name
    city_list.append(city)
    
#convert to DF
df = pd.DataFrame(city_list, columns = ["City"]) 

# dropping ALL duplicte values 
df.drop_duplicates(subset ="City", 
                     keep = False, inplace = True) 
  
# DF len = 536 unique cities
len(df)

#FOR TESTING
df = df.head()
df

        City
7   kargopol
9    winslow
11  progreso
16   bubaque
17  misratah

In [113]:
weather_data = []

for index, row in df.iterrows():
    weather_data.append(ow.get_current(row[0], **settings))

#weather_data

In [107]:
# Create an "extracts" object to get the temperature, latitude, and longitude in each city
summary = ["coord.lat", "coord.lon", "main.temp", "main.humidity","wind.speed", "clouds.all"]
cities = df['City'].values

# Create a Pandas DataFrame with the results
data = [response(*summary) for response in weather_data]
column_names = ['Latitude', 'Longitude', 'Temperature (F°)', 'Humidity', 'Wind (mph)', 'Clouds']
weather_data = pd.DataFrame(data, index=cities, columns=column_names)
weather_data

          Latitude  Longitude  Temperature (F°)  Humidity  Wind (mph)  Clouds
kargopol     61.51      38.95             36.27        89       12.95     100
winslow      51.94      -0.88             50.00        93       16.11     100
progreso    -34.68     -56.22             57.63        71        3.36       3
bubaque      11.28     -15.83             80.74        58       17.02       5
misratah     32.38      15.09             67.33        55        5.32       0